In [1]:
import pandas as pd
import numpy as np
import glob
from datetime import timedelta

In [2]:
ls

 Volume in drive C is Local Disk
 Volume Serial Number is FE3C-B042

 Directory of C:\Users\hyeji\Desktop\Penn_BootCamp\Homework\16_Tableau_City_Bike

08/01/2022  10:48 AM    <DIR>          .
08/01/2022  10:48 AM    <DIR>          ..
07/31/2022  08:19 PM    <DIR>          .ipynb_checkpoints
07/31/2022  10:19 PM    <DIR>          data
08/01/2022  10:48 AM             4,233 Data_Clean.ipynb
07/31/2022  08:19 PM             3,042 data_retreive.ipynb
07/14/2022  12:39 PM        20,005,759 JC-202206-citibike-tripdata.csv
07/29/2022  10:29 AM             8,549 README.md
07/31/2022  10:03 PM    <DIR>          Tableau-CityBike
               4 File(s)     20,021,583 bytes
               5 Dir(s)   5,881,753,600 bytes free

In [3]:
df_202206 = pd.read_csv("./data/202206-citbike-tripdata.csv", 
                        parse_dates=['started_at', 'ended_at'])

C:\Users\hyeji\AppData\Local\Temp\ipykernel_24184\765323423.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_202206 = pd.read_csv("./data/202206-citbike-tripdata.csv",

In [4]:
df_202206

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,FD85DE523427365B,classic_bike,2022-06-08 18:55:00,2022-06-08 18:58:13,E 149 St & Park Ave,7884.04,Morris Ave & E 153 St,7901.04,40.818154,-73.925294,40.820036,-73.921411,member
1,E1DF44B06B360036,classic_bike,2022-06-18 16:34:50,2022-06-18 16:47:49,E 115 St & Madison Ave,7599.02,W 148 St & Amsterdam Ave,8033.09,40.798983,-73.944716,40.827075,-73.945909,member
2,72B6DBF42BC1F9E1,classic_bike,2022-06-11 17:57:00,2022-06-11 18:07:33,E 115 St & Madison Ave,7599.02,2 Ave & E 99 St,7386.10,40.798944,-73.944846,40.786259,-73.945526,member
3,5FABA5CB97A6EA64,classic_bike,2022-06-23 17:32:04,2022-06-23 17:38:36,W Broadway & Spring St,5569.06,N Moore St & Hudson St,5470.02,40.724947,-74.001659,40.719961,-74.008443,member
4,EBA54764AA1A3A41,classic_bike,2022-06-30 16:17:43,2022-06-30 16:27:58,E 14 St & 1 Ave,5779.1,5 Ave & E 29 St,6248.06,40.731393,-73.982867,40.745168,-73.986831,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3432878,52758C21D58728B4,classic_bike,2022-06-25 00:45:19,2022-06-25 00:58:01,Norman St & Wyckoff Ave,4654.01,Grove St & Broadway,4526.01,40.695170,-73.903110,40.690470,-73.923511,casual
3432879,2F2B099B77266BF2,classic_bike,2022-06-21 16:52:08,2022-06-21 17:16:43,Railroad Ave & Kay Ave,4990.02,Grove St & Broadway,4526.01,40.705148,-73.970781,40.690470,-73.923511,member
3432880,AEE172A41A2FDA65,classic_bike,2022-06-29 17:58:20,2022-06-29 18:12:10,Bushwick Ave & Powers St,5250.05,S 4 St & Wythe Ave,5204.05,40.712477,-73.941000,40.712859,-73.965903,member
3432881,3E6A2E15FD49F94E,classic_bike,2022-06-16 19:31:34,2022-06-16 19:42:42,Bushwick Ave & Powers St,5250.05,S 4 St & Wythe Ave,5204.05,40.712477,-73.941000,40.712859,-73.965903,member
3432882,EA18E4BF86FD46F8,classic_bike,2022-06-16 12:15:02,2022-06-16 12:16:40,Broadway & W 51 St,6779.04,8 Ave & W 49 St,6747.07,40.762288,-73.983362,40.761712,-73.986551,member

In [5]:
df_202206.iloc[0, 2]

Timestamp('2022-06-08 18:55:00')

In [6]:
minutes_ = df_202206.iloc[:, 3] - df_202206.iloc[:, 2]
minutes_.min()

Timedelta('-1 days +23:49:46')

In [7]:
df_202206['tripduration'] = minutes_.dt.total_seconds()/60

df_202206.sort_values(by=['tripduration'])

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,tripduration
1769646,9BBE2898504AC191,electric_bike,2022-06-26 12:36:25,2022-06-26 12:26:11,Walker St & Baxter St,5351.07,Walker St & Baxter St,5351.07,40.717411,-73.999573,40.717411,-73.999573,member,-10.233333
1559580,0DD2457C3FAA3A4C,classic_bike,2022-06-13 17:43:18,2022-06-13 17:37:44,South St & Whitehall St,4846.01,South St & Whitehall St,4846.01,40.701221,-74.012342,40.701221,-74.012342,member,-5.566667
2455035,E38D5AC6FD9BAE0A,classic_bike,2022-06-13 17:43:02,2022-06-13 17:38:01,W 42 St & Dyer Ave,6644.07,W 42 St & Dyer Ave,6644.07,40.758985,-73.993800,40.758985,-73.993800,member,-5.016667
1398082,CE5B6B21E981BF36,classic_bike,2022-06-13 17:42:51,2022-06-13 17:38:13,1 Ave & E 30 St,6079.03,1 Ave & E 30 St,6079.03,40.741444,-73.975361,40.741444,-73.975361,casual,-4.633333
1760974,B537D8A253970DED,classic_bike,2022-06-19 12:07:48,2022-06-19 12:03:12,Walker St & Baxter St,5351.07,Walker St & Baxter St,5351.07,40.717411,-73.999573,40.717411,-73.999573,member,-4.600000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2858498,7D3B30F644D67ABF,docked_bike,2022-06-17 17:38:26,2022-07-09 07:06:29,Charlotte St & Boston Rd,8167.04,E 47 St & 2 Ave,6498.10,40.835877,-73.893143,40.753231,-73.970325,casual,31048.050000
2348715,C4C7F3571E343AC2,docked_bike,2022-06-13 10:10:41,2022-07-05 03:33:42,Willis Ave & E 137 St,7726.02,Rogers Pl & E 165 St,7987.14,40.808384,-73.923604,40.823884,-73.897403,casual,31283.016667
667130,767C8569F2EA1FAC,docked_bike,2022-06-04 15:30:19,2022-06-26 21:07:02,W 22 St & 10 Ave,6306.06,E 141 St & St Ann's Ave,7722.06,40.746920,-74.004519,40.808633,-73.916124,casual,32016.716667
404076,25045A7A7BFB3ADE,docked_bike,2022-06-12 05:26:40,2022-07-11 07:42:22,21 Ave & Shore Blvd,7342.01,Bushwick Ave & Linden St,4600.09,40.783956,-73.916894,40.691460,-73.921460,casual,41895.700000
368506,983E9C9E51014194,docked_bike,2022-06-01 14:39:13,2022-07-03 18:39:14,8 Ave & W 31 St,6450.05,Washington St & Barrow St,5847.08,40.750585,-73.994685,40.731911,-74.008769,casual,46320.016667

In [8]:
min_minutes = 30

def preprocess(df):
    minutes_ = df.iloc[:, 3] - df.iloc[:, 2]
    df['tripduration'] = minutes_.dt.total_seconds()/60
    df.iloc[:, -1] = round(df.iloc[:, -1])
    df_short = df[df.iloc[:, -1] >= min_minutes].copy()
    
    return df_short

In [9]:
preprocess(df_202206)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,tripduration
13,DB6B93E416D02850,classic_bike,2022-06-18 18:42:32,2022-06-18 19:12:48,1 Pl & Clinton St,4193.14,Park Cir & East Dr,3344.02,40.680959,-73.999057,40.651566,-73.972212,member,30.0
21,FB5C732D3DAFB52C,classic_bike,2022-06-26 20:38:33,2022-06-26 21:20:20,1 Pl & Clinton St,4193.14,Evergreen Ave & Noll St,4873.08,40.680959,-73.999057,40.701060,-73.933180,member,42.0
48,917D4037B314554A,classic_bike,2022-06-16 11:58:07,2022-06-16 12:47:17,W Broadway & Spring St,5569.06,Gansevoort St & Hudson St,6072.14,40.725106,-74.001646,40.739448,-74.005070,member,49.0
55,67E08398A1664460,classic_bike,2022-06-29 10:46:19,2022-06-29 12:32:25,Henry St & Middagh St,4861.05,Henry St & Middagh St,4861.05,40.700300,-73.991581,40.700300,-73.991581,member,106.0
61,E6F80789C691AE0F,classic_bike,2022-06-10 14:17:40,2022-06-10 14:58:55,E 118 St & Park Ave,7625.18,E 118 St & Park Ave,7625.18,40.800449,-73.941722,40.800539,-73.941995,member,41.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3432829,F5A75FFF5AEA226C,electric_bike,2022-06-22 15:37:25,2022-06-22 16:34:09,Kent Ave & Division Ave,5021.05,S 4 St & Wythe Ave,5204.05,40.706564,-73.968319,40.712859,-73.965903,member,57.0
3432851,F7E5C91ABF9FA790,docked_bike,2022-06-26 19:32:50,2022-06-26 20:16:05,St Marks Pl & 2 Ave,5669.1,8 Ave & W 49 St,6747.07,40.728419,-73.987140,40.761712,-73.986551,casual,43.0
3432864,2EF7A2DEA7E43476,classic_bike,2022-06-29 09:53:15,2022-06-29 22:28:52,59 St & 5 Ave,2961.05,45 St & 4 Ave,3275.03,40.640125,-74.015726,40.649145,-74.009486,casual,756.0
3432873,AD06D2FC859519F0,classic_bike,2022-06-13 11:11:43,2022-06-13 11:43:08,Forsyth St & Canal St,5270.07,8 Ave & W 49 St,6747.07,40.715815,-73.994224,40.761712,-73.986551,member,31.0
3432875,DBF8F36A60820F45,classic_bike,2022-06-03 23:22:12,2022-06-04 00:07:11,Garfield Pl & 8 Ave,3978.13,Wyckoff Av & Jefferson St,5051.01,40.671198,-73.974841,40.707165,-73.923711,casual,45.0

In [10]:
files_to_merge = [file for file in glob.glob(r'data/*.csv')]

In [11]:
files_to_merge

['data\\202104-citibike-tripdata.csv',
 'data\\202105-citibike-tripdata.csv',
 'data\\202106-citibike-tripdata.csv',
 'data\\202107-citibike-tripdata.csv',
 'data\\202108-citibike-tripdata.csv',
 'data\\202109-citibike-tripdata.csv',
 'data\\202110-citibike-tripdata.csv',
 'data\\202111-citibike-tripdata.csv',
 'data\\202112-citibike-tripdata.csv',
 'data\\202201-citibike-tripdata.csv',
 'data\\202202-citibike-tripdata.csv',
 'data\\202203-citibike-tripdata.csv',
 'data\\202204-citibike-tripdata.csv',
 'data\\202205-citibike-tripdata.csv',
 'data\\202206-citbike-tripdata.csv']

In [12]:
number_of_cols = list()

for file in files_to_merge:
    df = pd.read_csv(file, nrows=0)
    number_of_cols.append(df.columns.size)
    
print(f"Maximum number of columns: {max(number_of_cols)}")
print(f"Maximum number of columns: {max(number_of_cols)}")

Maximum number of columns: 13
Maximum number of columns: 13

In [13]:
col_names = pd.concat([pd.read_csv(file, nrows = 0) for file in files_to_merge], 
                      ignore_index = True).columns
col_names

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='object')

In [14]:
data_list = list()

for file in files_to_merge:

    df = pd.read_csv(file, parse_dates=['started_at', 'ended_at'])

    # Preprocess each dataframe
    processed_df = preprocess(df)
    
    # Append each dataframe to the data_list
    data_list.append(processed_df)

C:\Users\hyeji\AppData\Local\Temp\ipykernel_24184\3113461086.py:5: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, parse_dates=['started_at', 'ended_at'])
C:\Users\hyeji\AppData\Local\Temp\ipykernel_24184\3113461086.py:5: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, parse_dates=['started_at', 'ended_at'])
C:\Users\hyeji\AppData\Local\Temp\ipykernel_24184\3113461086.py:5: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, parse_dates=['started_at', 'ended_at'])
C:\Users\hyeji\AppData\Local\Temp\ipykernel_24184\3113461086.py:5: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, parse_dates=['started_at', 'ended_at'])
C:\Users\hyeji\AppData\Local\Temp\ipykernel_24184\3113461086.py:5: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, parse_dates=['started_at', 'ended_at'])
C:\Users\hyeji\AppData\Local\Temp\ipykernel_24184\3113461086.py:5: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, parse_dates=['started_at', 'ended_at'])
C:\Users\hyeji\AppData\Local\Temp\ipykernel_24184\3113461086.py:5: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, parse_dates=['started_at', 'ended_at'])
C:\Users\hyeji\AppData\Local\Temp\ipykernel_24184\3113461086.py:5: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, parse_dates=['started_at', 'ended_at'])
C:\Users\hyeji\AppData\Local\Temp\ipykernel_24184\3113461086.py:5: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, parse_dates=['started_at', 'ended_at'])
C:\Users\hyeji\AppData\Local\Temp\ipykernel_24184\3113461086.py:5: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, parse_dates=['started_at', 'ended_at'])
C:\Users\hyeji\AppData\Local\Temp\ipykernel_24184\3113461086.py:5: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, parse_dates=['started_at', 'ended_at'])
C:\Users\hyeji\AppData\Local\Temp\ipykernel_24184\3113461086.py:5: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, parse_dates=['started_at', 'ended_at'])
C:\Users\hyeji\AppData\Local\Temp\ipykernel_24184\3113461086.py:5: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, parse_dates=['started_at', 'ended_at'])
C:\Users\hyeji\AppData\Local\Temp\ipykernel_24184\3113461086.py:5: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, parse_dates=['started_at', 'ended_at'])
C:\Users\hyeji\AppData\Local\Temp\ipykernel_24184\3113461086.py:5: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, parse_dates=['started_at', 'ended_at'])

In [15]:
# Conso list of dataframes into one dataframe
conso_df = pd.concat(data_list)

# Drop duplicates
conso_df.drop_duplicates(inplace=True)

In [20]:
conso_df.sort_values(by=['started_at'])

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,tripduration
1441068,CE586BA95ED6E20B,docked_bike,2021-04-01 00:00:19,2021-04-01 02:07:52,8 Ave & W 52 St,6816.07,7 Ave & Central Park South,6912.01,40.763707,-73.985161,40.766741,-73.979069,member,128.0
1025755,1F949EE66D451F6D,docked_bike,2021-04-01 00:05:31,2021-04-01 02:32:28,Hamilton Pl & W 138 St,7920.01,W 171 St & St. Nicholas Ave,8262.07,40.821728,-73.952761,40.842941,-73.938631,casual,147.0
1048214,4332335B528CE782,docked_bike,2021-04-01 00:07:00,2021-04-01 00:54:18,Pier 40 - Hudson River Park,5696.03,E 14 St & Avenue B,5736.09,40.727714,-74.011295,40.729387,-73.977724,casual,47.0
1048265,098A9EB58274B4F4,docked_bike,2021-04-01 00:07:22,2021-04-01 00:54:33,Pier 40 - Hudson River Park,5696.03,E 14 St & Avenue B,5736.09,40.727714,-74.011295,40.729387,-73.977724,member,47.0
1306196,723B7D2F49E7CC8E,docked_bike,2021-04-01 00:12:38,2021-04-01 00:42:52,Frederick Douglass Blvd & W 129 St,7795.09,Frederick Douglass Blvd & W 129 St,7795.09,40.812551,-73.949228,40.812551,-73.949229,member,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2912600,0C0A1300C9F3C338,classic_bike,2022-06-30 23:58:41,2022-07-01 00:58:48,Willoughby Ave & Tompkins Ave,4665.02,NaN,NaN,40.694243,-73.946359,40.720000,-73.970000,member,60.0
2513448,C080540775F1611E,classic_bike,2022-06-30 23:59:03,2022-07-01 00:35:26,2 Ave & E 125 St,7648.16,2 Ave & E 125 St,7648.16,40.802553,-73.933609,40.802554,-73.933509,member,36.0
2521802,4B5F31787CFAA952,electric_bike,2022-06-30 23:59:13,2022-07-01 00:29:59,W 42 St & 8 Ave,6602.05,West Thames St,5114.06,40.757570,-73.990985,40.708347,-74.017134,casual,31.0
1258044,620A7E735BC51ABA,classic_bike,2022-06-30 23:59:32,2022-07-01 00:34:08,7 Ave & Central Park South,6912.01,Concourse Village East & E 158 St,8000.02,40.766390,-73.979334,40.823732,-73.919379,member,35.0
1294200,8B6ACDF9AF9DD35B,docked_bike,2022-06-30 23:59:33,2022-07-01 00:30:24,Pearl St & Hanover Square,4993.02,Broadway & Battery Pl,4962.01,40.704718,-74.009260,40.704633,-74.013617,casual,31.0

In [22]:
conso_df.loc[conso_df['ride_id'] == "C96B5887B8F6E324"]

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,tripduration
2864298,C96B5887B8F6E324,electric_bike,2021-06-11 15:22:18,2021-10-24 17:46:03,Riverside Dr & W 78 St,7340.06,E 25 St & 2 Ave,6046.02,40.784144,-73.983624,40.739126,-73.979738,casual,194544.0

In [17]:
conso_df.rideable_type.unique()

array(['docked_bike', 'electric_bike', 'classic_bike'], dtype=object)

In [18]:
conso_df.to_csv("data/conso_file.csv", index=False)